/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaregiverRealityCheckRouteImport } from './routes/caregiver-reality-check'
import { Route as DementiaTriggerDecoderRouteImport } from './routes/dementia-trigger-decoder'
import { Route as EducationHubRouteImport } from './routes/education-hub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRealityCheckRoute = CaregiverRealityCheckRouteImport.update({
  id: '/caregiver-reality-check',
  path: '/caregiver-reality-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DementiaTriggerDecoderRoute = DementiaTriggerDecoderRouteImport.update({
  id: '/dementia-trigger-decoder',
  path: '/dementia-trigger-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationHubRoute = EducationHubRouteImport.update({
  id: '/education-hub',
  path: '/education-hub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caregiver-reality-check': typeof CaregiverRealityCheckRoute
  '/dementia-trigger-decoder': typeof DementiaTriggerDecoderRoute
  '/education-hub': typeof EducationHubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caregiver-reality-check': typeof CaregiverRealityCheckRoute
  '/dementia-trigger-decoder': typeof DementiaTriggerDecoderRoute
  '/education-hub': typeof EducationHubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caregiver-reality-check': typeof CaregiverRealityCheckRoute
  '/dementia-trigger-decoder': typeof DementiaTriggerDecoderRoute
  '/education-hub': typeof EducationHubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/caregiver-reality-check'
    | '/dementia-trigger-decoder'
    | '/education-hub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/caregiver-reality-check'
    | '/dementia-trigger-decoder'
    | '/education-hub'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/caregiver-reality-check'
    | '/dementia-trigger-decoder'
    | '/education-hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaregiverRealityCheckRoute: typeof CaregiverRealityCheckRoute
  DementiaTriggerDecoderRoute: typeof DementiaTriggerDecoderRoute
  EducationHubRoute: typeof EducationHubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver-reality-check': {
      id: '/caregiver-reality-check'
      path: '/caregiver-reality-check'
      fullPath: '/caregiver-reality-check'
      preLoaderRoute: typeof CaregiverRealityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dementia-trigger-decoder': {
      id: '/dementia-trigger-decoder'
      path: '/dementia-trigger-decoder'
      fullPath: '/dementia-trigger-decoder'
      preLoaderRoute: typeof DementiaTriggerDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-hub': {
      id: '/education-hub'
      path: '/education-hub'
      fullPath: '/education-hub'
      preLoaderRoute: typeof EducationHubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaregiverRealityCheckRoute: CaregiverRealityCheckRoute,
  DementiaTriggerDecoderRoute: DementiaTriggerDecoderRoute,
  EducationHubRoute: EducationHubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
